#!/bin/bash

#export ROS_MASTER_URI=http://10.42.0.59:11311
#export ROS_MASTER_URI=http://Team2107.local:11311

export ROS_IP=$(hostname -I | awk '{print $1}') #10.42.0.59 

rosrun merl_bot laptop.py
