#!/bin/bash

#Testing code

gnome-terminal -e "roscore"
sleep 2
gnome-terminal -e "rosrun cv_camera cv_camera_node"
sleep 2
gnome-terminal -e "rosrun merl_bot ros_node_pi.py"
rosrun merl_bot ros_node_laptop.py
